"""add assignment.filename_template column

Revision ID: 3f16ac026ce9
Revises: 4341760849cd
Create Date: 2026-05-19 13:00:53.172687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f16ac026ce9'
down_revision: Union[str, Sequence[str], None] = '4341760849cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('filename_template', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'filename_template')
    # ### end Alembic commands ###
