"""add token_prefix to trusted_devices

Revision ID: 4341760849cd
Revises: f4316cc96cce
Create Date: 2026-05-18 15:53:55.819210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4341760849cd'
down_revision: Union[str, Sequence[str], None] = 'f4316cc96cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_devices', sa.Column('token_prefix', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_trusted_devices_token_prefix'), 'trusted_devices', ['token_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_devices_token_prefix'), table_name='trusted_devices')
    op.drop_column('trusted_devices', 'token_prefix')
    # ### end Alembic commands ###
