"""add classroom collaborative docs (Document, DocumentMember, DocumentRevision)

Revision ID: 4f4e265df128
Revises: 67cf4c6d9bc9
Create Date: 2026-05-19 14:33:18.051401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4e265df128'
down_revision: Union[str, Sequence[str], None] = '67cf4c6d9bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('yjs_state', sa.LargeBinary(), nullable=True),
    sa.Column('plain_text', sa.Text(), nullable=True),
    sa.Column('access_mode', sa.String(length=30), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['classroom_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_docs_course_id', 'classroom_docs', ['course_id'], unique=False)
    op.create_index('ix_classroom_docs_owner_id', 'classroom_docs', ['owner_id'], unique=False)
    op.create_table('classroom_doc_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['classroom_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_doc_member')
    )
    op.create_index('ix_classroom_doc_members_document_id', 'classroom_doc_members', ['document_id'], unique=False)
    op.create_index('ix_classroom_doc_members_user_id', 'classroom_doc_members', ['user_id'], unique=False)
    op.create_table('classroom_doc_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('yjs_state', sa.LargeBinary(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['classroom_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_doc_revisions_created_at', 'classroom_doc_revisions', ['created_at'], unique=False)
    op.create_index('ix_classroom_doc_revisions_document_id', 'classroom_doc_revisions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_doc_revisions_document_id', table_name='classroom_doc_revisions')
    op.drop_index('ix_classroom_doc_revisions_created_at', table_name='classroom_doc_revisions')
    op.drop_table('classroom_doc_revisions')
    op.drop_index('ix_classroom_doc_members_user_id', table_name='classroom_doc_members')
    op.drop_index('ix_classroom_doc_members_document_id', table_name='classroom_doc_members')
    op.drop_table('classroom_doc_members')
    op.drop_index('ix_classroom_docs_owner_id', table_name='classroom_docs')
    op.drop_index('ix_classroom_docs_course_id', table_name='classroom_docs')
    op.drop_table('classroom_docs')
    # ### end Alembic commands ###
