"""add classroom course/student/post

Revision ID: 67cf4c6d9bc9
Revises: 3f16ac026ce9
Create Date: 2026-05-19 13:45:22.707338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cf4c6d9bc9'
down_revision: Union[str, Sequence[str], None] = '3f16ac026ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('class_name', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'teacher_id', 'subject', 'class_name', name='uq_course_semester_teacher_subject_class')
    )
    op.create_index('ix_classroom_courses_semester_id', 'classroom_courses', ['semester_id'], unique=False)
    op.create_index('ix_classroom_courses_teacher_id', 'classroom_courses', ['teacher_id'], unique=False)
    op.create_table('classroom_course_students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['classroom_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id', name='uq_course_student')
    )
    op.create_index('ix_course_students_course_id', 'classroom_course_students', ['course_id'], unique=False)
    op.create_index('ix_course_students_student_id', 'classroom_course_students', ['student_id'], unique=False)
    op.create_table('classroom_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['classroom_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_posts_course_id', 'classroom_posts', ['course_id'], unique=False)
    op.create_index('ix_classroom_posts_post_type', 'classroom_posts', ['post_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_posts_post_type', table_name='classroom_posts')
    op.drop_index('ix_classroom_posts_course_id', table_name='classroom_posts')
    op.drop_table('classroom_posts')
    op.drop_index('ix_course_students_student_id', table_name='classroom_course_students')
    op.drop_index('ix_course_students_course_id', table_name='classroom_course_students')
    op.drop_table('classroom_course_students')
    op.drop_index('ix_classroom_courses_teacher_id', table_name='classroom_courses')
    op.drop_index('ix_classroom_courses_semester_id', table_name='classroom_courses')
    op.drop_table('classroom_courses')
    # ### end Alembic commands ###
