"""add semester is_archived

Revision ID: 92ee67e77ac7
Revises: 350f634ff281
Create Date: 2026-05-18 12:45:09.615937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ee67e77ac7'
down_revision: Union[str, Sequence[str], None] = '350f634ff281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semesters', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('semesters', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semesters', 'archived_at')
    op.drop_column('semesters', 'is_archived')
    # ### end Alembic commands ###
