"""add classroom_posts assignment meta (due_date max_score topic attachments)

Revision ID: c6fddf807401
Revises: dd2545140022
Create Date: 2026-05-20 00:39:19.740735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fddf807401'
down_revision: Union[str, Sequence[str], None] = 'dd2545140022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom_posts', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('classroom_posts', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('classroom_posts', sa.Column('topic', sa.String(length=100), nullable=True))
    op.add_column('classroom_posts', sa.Column('attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom_posts', 'attachments')
    op.drop_column('classroom_posts', 'topic')
    op.drop_column('classroom_posts', 'max_score')
    op.drop_column('classroom_posts', 'due_date')
    # ### end Alembic commands ###
