"""add classroom surveys (Survey, Question, Response, Answer)

Revision ID: c7d1710fc06d
Revises: 4f4e265df128
Create Date: 2026-05-19 19:34:43.025788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d1710fc06d'
down_revision: Union[str, Sequence[str], None] = '4f4e265df128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple_responses', sa.Boolean(), nullable=False),
    sa.Column('access_mode', sa.String(length=30), nullable=False),
    sa.Column('open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['classroom_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_surveys_author_id', 'classroom_surveys', ['author_id'], unique=False)
    op.create_index('ix_classroom_surveys_course_id', 'classroom_surveys', ['course_id'], unique=False)
    op.create_index('ix_classroom_surveys_status', 'classroom_surveys', ['status'], unique=False)
    op.create_table('classroom_survey_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('rating_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['classroom_surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_survey_questions_order', 'classroom_survey_questions', ['survey_id', 'order'], unique=False)
    op.create_index('ix_classroom_survey_questions_survey_id', 'classroom_survey_questions', ['survey_id'], unique=False)
    op.create_table('classroom_survey_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['classroom_surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_survey_responses_respondent_id', 'classroom_survey_responses', ['respondent_id'], unique=False)
    op.create_index('ix_classroom_survey_responses_survey_id', 'classroom_survey_responses', ['survey_id'], unique=False)
    op.create_table('classroom_survey_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('choice_values', sa.JSON(), nullable=True),
    sa.Column('rating_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['classroom_survey_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['classroom_survey_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_survey_answer')
    )
    op.create_index('ix_classroom_survey_answers_question_id', 'classroom_survey_answers', ['question_id'], unique=False)
    op.create_index('ix_classroom_survey_answers_response_id', 'classroom_survey_answers', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_survey_answers_response_id', table_name='classroom_survey_answers')
    op.drop_index('ix_classroom_survey_answers_question_id', table_name='classroom_survey_answers')
    op.drop_table('classroom_survey_answers')
    op.drop_index('ix_classroom_survey_responses_survey_id', table_name='classroom_survey_responses')
    op.drop_index('ix_classroom_survey_responses_respondent_id', table_name='classroom_survey_responses')
    op.drop_table('classroom_survey_responses')
    op.drop_index('ix_classroom_survey_questions_survey_id', table_name='classroom_survey_questions')
    op.drop_index('ix_classroom_survey_questions_order', table_name='classroom_survey_questions')
    op.drop_table('classroom_survey_questions')
    op.drop_index('ix_classroom_surveys_status', table_name='classroom_surveys')
    op.drop_index('ix_classroom_surveys_course_id', table_name='classroom_surveys')
    op.drop_index('ix_classroom_surveys_author_id', table_name='classroom_surveys')
    op.drop_table('classroom_surveys')
    # ### end Alembic commands ###
