"""add survey.response_edit_minutes

Revision ID: dd2545140022
Revises: e58ebf1bfb9f
Create Date: 2026-05-19 20:34:15.583469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2545140022'
down_revision: Union[str, Sequence[str], None] = 'e58ebf1bfb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: 기존 행이 있는 DB에서 NOT NULL 컬럼을 추가하려면 server_default 필수.
    autogenerate가 빠뜨려서 수동 보강 (CLAUDE.md "과거 마이그레이션 절대 수정 X"는
    이미 적용 후에 해당 — 본 revision은 보강 후 dev/prod 모두 신규 적용 기준).
    """
    op.add_column(
        'classroom_surveys',
        sa.Column(
            'response_edit_minutes',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    # 서버 기본값은 향후 변경(ORM default가 사용)되도록 제거 — backfill만 위해 사용.
    op.alter_column('classroom_surveys', 'response_edit_minutes', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom_surveys', 'response_edit_minutes')
    # ### end Alembic commands ###
