"""add classroom_shortlinks

Revision ID: e58ebf1bfb9f
Revises: c7d1710fc06d
Create Date: 2026-05-19 19:47:01.299299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58ebf1bfb9f'
down_revision: Union[str, Sequence[str], None] = 'c7d1710fc06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_shortlinks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_classroom_shortlinks_created_by_id', 'classroom_shortlinks', ['created_by_id'], unique=False)
    op.create_index('ix_classroom_shortlinks_slug', 'classroom_shortlinks', ['slug'], unique=True)
    op.create_index('ix_classroom_shortlinks_target', 'classroom_shortlinks', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_shortlinks_target', table_name='classroom_shortlinks')
    op.drop_index('ix_classroom_shortlinks_slug', table_name='classroom_shortlinks')
    op.drop_index('ix_classroom_shortlinks_created_by_id', table_name='classroom_shortlinks')
    op.drop_table('classroom_shortlinks')
    # ### end Alembic commands ###
