"""add classroom presentations (deck slide member)

Revision ID: fe22f6d02a16
Revises: c6fddf807401
Create Date: 2026-05-20 01:23:01.288592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe22f6d02a16'
down_revision: Union[str, Sequence[str], None] = 'c6fddf807401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_presentations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('yjs_state', sa.LargeBinary(), nullable=True),
    sa.Column('access_mode', sa.String(length=30), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['classroom_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_presentations_course_id', 'classroom_presentations', ['course_id'], unique=False)
    op.create_index('ix_classroom_presentations_owner_id', 'classroom_presentations', ['owner_id'], unique=False)
    op.create_table('classroom_presentation_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['classroom_presentations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presentation_id', 'user_id', name='uq_presentation_member')
    )
    op.create_index('ix_classroom_presentation_members_presentation_id', 'classroom_presentation_members', ['presentation_id'], unique=False)
    op.create_index('ix_classroom_presentation_members_user_id', 'classroom_presentation_members', ['user_id'], unique=False)
    op.create_table('classroom_slides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('plain_text', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['classroom_presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classroom_slides_order', 'classroom_slides', ['presentation_id', 'order'], unique=False)
    op.create_index('ix_classroom_slides_presentation_id', 'classroom_slides', ['presentation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_slides_presentation_id', table_name='classroom_slides')
    op.drop_index('ix_classroom_slides_order', table_name='classroom_slides')
    op.drop_table('classroom_slides')
    op.drop_index('ix_classroom_presentation_members_user_id', table_name='classroom_presentation_members')
    op.drop_index('ix_classroom_presentation_members_presentation_id', table_name='classroom_presentation_members')
    op.drop_table('classroom_presentation_members')
    op.drop_index('ix_classroom_presentations_owner_id', table_name='classroom_presentations')
    op.drop_index('ix_classroom_presentations_course_id', table_name='classroom_presentations')
    op.drop_table('classroom_presentations')
    # ### end Alembic commands ###
